### ISSUE TITLE
Found an ODM that produces parse errors and won't load, "undefined entity"

### ISSUE THREAD

**Issue by wtanksleyjr** [ping/odmpy#19]
I get the following backtrace when running odmpy on the attached ODM file; the cause is either the `&#34;` or the `&eacute;`, confirmed by editing them both out, it loaded just fine.

Hm, not sure how to attach, I'll submit this and see if I can figure it out.

```
Traceback (most recent call last):
  File "/home/william/.local/bin/odmpy", line 8, in <module>
    sys.exit(main())
  File "/home/william/.local/lib/python3.8/site-packages/odmpy/__main__.py", line 26, in main
    run()
  File "/home/william/.local/lib/python3.8/site-packages/odmpy/odm.py", line 231, in run
    metadata = xml.etree.ElementTree.fromstring(
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: undefined entity: line 1, column 1136
./fetchodm.sh: cannot odmpy dl -r 10 -k -d /mnt/hdd-8TB/sharing/downloads/pyodm-dl/tmp.H7nwXYVOpa /mnt/hdd-8TB/sharing/downloads/pyodm-dl/tmp.H7nwXYVOpa/SkylarkofSpace9781596078707.odm
```

**Comment by wtanksleyjr** [comment]
https://gist.github.com/wtanksleyjr/f9139dd6f9426cf84f352cc6e8be021f

**Comment by ping** [comment]
It's the `&eacute;`. Pushed out a quick fix with version 0.4.4.

**Comment by wtanksleyjr** [comment]
Thank you, confirmed!

**Comment by wtanksleyjr** [comment]
This is closed, but I just hit another ODM with the same error from a different "undefined entity" -- again, I just manually edited them out, but perhaps a more general fix is needed, since there's really no need to expand any entities at all.

The culprit is one or all of the following:

```
&ldquo;
&rdquo;
&rsquo;
```

**Comment by ping** [comment]
Fixed in 0.4.5.

**Comment by wtanksleyjr** [comment]
Since this is still open I'll reuse it -- this time `&nbsp;` killed my ODM. Again, editing it out made everything fine.

```
Traceback (most recent call last):
  File "/home/william/.local/lib/python3.8/site-packages/odmpy/odm.py", line 190, in run
    metadata = xml.etree.ElementTree.fromstring(text)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: undefined entity: line 1, column 1079

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/william/.local/bin/odmpy", line 8, in <module>
    sys.exit(main())
  File "/home/william/.local/lib/python3.8/site-packages/odmpy/__main__.py", line 26, in main
    run()
  File "/home/william/.local/lib/python3.8/site-packages/odmpy/odm.py", line 201, in run
    metadata = xml.etree.ElementTree.fromstring(patched_text)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: undefined entity: line 1, column 5460
FAIL
```

**Comment by ping** [comment]
@wtanksleyjr Sorry about that, fixed in 0.4.6.

**Comment by ping** [comment]
Closing this since there hasn't been new reports about this in a while.
