### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by jvandervort** [ping/odmpy#34]
```
Current Head:
commit 0f769e71b25c3ce64917b52f195cc47401cdbe9d (HEAD -> master, ping/master)
Author: ping <ping@users.noreply.github.com>
Date:   Sat Feb 18 16:23:10 2023 +0800
```

```
======================================================================
ERROR: test_loans (tests.libby_tests.LibbyClientTests.test_loans)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\nnn\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nnn\AppData\Roaming\Python\Python311\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\nnn\AppData\Roaming\Python\Python311\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nnn\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nnn\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\nnn\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\nnn\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\nnn\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000001C38FD14550>, 'Connection to sentry-read.svc.overdrive.com timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nnn\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\nnn\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\nnn\AppData\Roaming\Python\Python311\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sentry-read.svc.overdrive.com', port=443): Max retries exceeded with url: /chip/sync (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001C38FD14550>, 'Connection to sentry-read.svc.overdrive.com timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nnn\Documents\dev\odmpy\odmpy\libby.py", line 309, in make_request
    res = session.send(
          ^^^^^^^^^^^^^
  File "C:\Users\nnn\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nnn\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='sentry-read.svc.overdrive.com', port=443): Max retries exceeded with url: /chip/sync (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001C38FD14550>, 'Connection to sentry-read.svc.overdrive.com timed out. (connect timeout=10)'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\nnn\Documents\dev\odmpy\tests\libby_tests.py", line 245, in test_loans
    res = self.client.get_loans()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nnn\Documents\dev\odmpy\odmpy\libby.py", line 515, in get_loans
    return self.sync().get("loans", [])
           ^^^^^^^^^^^
  File "C:\Users\nnn\Documents\dev\odmpy\odmpy\libby.py", line 409, in sync
    res: Dict = self.make_request("chip/sync")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nnn\Documents\dev\odmpy\odmpy\libby.py", line 321, in make_request
    raise ClientConnectionError(str(conn_err)) from conn_err
odmpy.libby_errors.ClientConnectionError: <odmpy.libby_errors.ClientConnectionError; http_status=0, msg='HTTPSConnectionPool(host='sentry-read.svc.overdrive.com', port=443): Max retries exceeded with url: /chip/sync (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001C38FD14550>, 'Connection to sentry-read.svc.overdrive.com timed out. (connect timeout=10)'))', error_response='''>
```

**Comment by ping** [comment]
This looks like a temporal/connection problem. The test will probably pass on a re-run.

I've bumped up the retries and timeout for this set of tests anyway.

**Comment by jvandervort** [comment]
Looks good, all tests pass!
