### ISSUE TITLE
odmpy crashes when downloading audiobooks on 0.8.1

### ISSUE THREAD

**Issue by crownsox** [ping/odmpy#55]
odmpy crashes when trying to download an audiobook with the libby command. I've included the command and crash output below. I was able to revert to odmpy-0.8.0 and execute the same command without this issue.

**Relevant command line information**
Base command `odmpy libby -m -c --nobookfolder --ebooks --direct --settings ~/.odmpy/`

Resulting output (with intermediate audiobook selection)
```
odmpy Interactive Client for Libby
----------------------------------------------------------------------
Found 2 loans.
 1: Homeward Bound                                   🎧 Elaine Tyler May
    * Expires: 2023-10-25  REDACTED
 2: Dealing with China                               🎧 Henry M. Paulson Jr.
    * Expires: 2023-10-25  REDACTED

Download. Choose from 1-2 (separate choices with a space or leave blank to quit),
then press enter: 1 2
Opening audiobook "Homeward Bound"...
An unexpected error has occurred
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/odmpy/odm.py", line 1175, in run
    openbook, toc = libby_client.process_audiobook(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/odmpy/libby.py", line 835, in process_audiobook
    download_base, meta = self.prepare_loan(loan)
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/odmpy/libby.py", line 817, in prepare_loan
    _ = self.make_request(
        ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/odmpy/libby.py", line 366, in make_request
    ErrorHandler.process(http_err)
  File "/opt/homebrew/lib/python3.11/site-packages/odmpy/libby_errors.py", line 86, in process
    error = http_err.response.json()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/odmpy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/odmpy/__main__.py", line 27, in main
    run()
  File "/opt/homebrew/lib/python3.11/site-packages/odmpy/odm.py", line 1175, in run
    openbook, toc = libby_client.process_audiobook(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/odmpy/libby.py", line 835, in process_audiobook
    download_base, meta = self.prepare_loan(loan)
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/odmpy/libby.py", line 817, in prepare_loan
    _ = self.make_request(
        ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/odmpy/libby.py", line 366, in make_request
    ErrorHandler.process(http_err)
  File "/opt/homebrew/lib/python3.11/site-packages/odmpy/libby_errors.py", line 86, in process
    error = http_err.response.json()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Version/Environment**
odmpy-0.8.1

**Comment by ping** [comment]
I am unable to replicate this error with the same title.

If you're up for some testing, can you go back to 0.8.1 and try with `--verbose` logging enabled. This will enable the print out of the HTTP requests and responses sent back and forth with libby. Then extract the last HTTP response received just before the error occurs and report back here?

`odmpy --verbose libby -m -c --nobookfolder --ebooks --direct --settings ~/.odmpy/`

**Comment by crownsox** [comment]
I was also unable to replicate my own error after re-upgrading to odmpy 0.8.1. I'm not sure why it failed last time. I don't believe anything in my setup changed.

I will close this issue accordingly.
