### ISSUE TITLE
Unable to access Libby through odmpy due to Traceback error

### ISSUE THREAD

**Issue by eckie** [ping/odmpy#66]
Hi, I was wondering if odmpy is still being maintained? I am hoping so! Starting Friday, April 19. I have been unable to access my library books in Libby.

**To Reproduce**
I'm am on a Mac with OS Sonoma using odmpy Version 0.8.1. [Python 3.11.3-darwin]
In Terminal, if I enter odmpy libby, or my usual command line sequence to access and download my libarary books: "odmpy libby -m -c -d "audiobooks/" I get the following:

**Version/Environment**
Please paste the contents of `odmpy --version` here.
odmpy Interactive Client for Libby
----------------------------------------------------------------------
An unexpected error has occurred
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/odmpy/libby.py", line 357, in make_request
    res.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://sentry-read.svc.overdrive.com/chip/sync

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/odmpy/odm.py", line 846, in run
    synced_state = libby_client.sync()
                   ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/odmpy/libby.py", line 457, in sync
    res: Dict = self.make_request("chip/sync")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/odmpy/libby.py", line 366, in make_request
    ErrorHandler.process(http_err)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/odmpy/libby_errors.py", line 103, in process
    raise ClientError(
odmpy.libby_errors.ClientError: <odmpy.libby_errors.ClientError; http_status=403, msg='403 Client Error: Forbidden for url: https://sentry-read.svc.overdrive.com/chip/sync', error_response='{"result":"missing_chip"}''>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/odmpy/libby.py", line 357, in make_request
    res.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://sentry-read.svc.overdrive.com/chip/sync

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/odmpy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/odmpy/__main__.py", line 27, in main
    run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/odmpy/odm.py", line 846, in run
    synced_state = libby_client.sync()
                   ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/odmpy/libby.py", line 457, in sync
    res: Dict = self.make_request("chip/sync")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/odmpy/libby.py", line 366, in make_request
    ErrorHandler.process(http_err)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/odmpy/libby_errors.py", line 103, in process
    raise ClientError(
odmpy.libby_errors.ClientError: <odmpy.libby_errors.ClientError; http_status=403, msg='403 Client Error: Forbidden for url: https://sentry-read.svc.overdrive.com/chip/sync', error_response='{"result":"missing_chip"}''>

----------------------------------------------------------------------------------------------------------------
I love this app and am going to "send you a coffee" in hopes that this is still being maintained a fix or some help can be provided. Thanks you!

**Comment by eckie** [comment]
Sorry! I didn't think to look at previously closed issues until after I posted this.  If anyone else is encountering this problem, please see: https://github.com/ping/odmpy/issues/62. 

You just need to reset your libby account in odmpy, and generate a new code. Instructions are in the ticket linked abouve.
