### ISSUE TITLE
Magazines not downloading  -- Error below

### ISSUE THREAD

**Issue by Gaylaric** [ping/odmpy#67]
Download. Choose from 1-71 (separate choices with a space or leave blank to quit),
then press enter: 3
Opening magazine "Louisiana Cookin'"...
An unexpected error has occurred
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\odmpy\odm.py", line 1228, in run
    extract_loan_file(libby_client, selected_loan, args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\odmpy\odm.py", line 384, in extract_loan_file
    _, openbook, rosters = libby_client.process_ebook(selected_loan)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\odmpy\libby.py", line 850, in process_ebook
    openbook = self.make_request(meta["urls"]["openbook"])
                                 ~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'openbook'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Scripts\odmpy.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\odmpy\__main__.py", line 27, in main
    run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\odmpy\odm.py", line 1228, in run
    extract_loan_file(libby_client, selected_loan, args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\odmpy\odm.py", line 384, in extract_loan_file
    _, openbook, rosters = libby_client.process_ebook(selected_loan)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\odmpy\libby.py", line 850, in process_ebook
    openbook = self.make_request(meta["urls"]["openbook"])
                                 ~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'openbook'

**Comment by valthewu** [comment]
same here! on 2 different Macs! No solution yet? thank you!
