### ISSUE TITLE
403 Forbidden Error 

### ISSUE THREAD

**Issue by warthog3** [ping/odmpy#69]
**Describe the problem**
Seeing this new error when trying to start odmpy

`odmpy libby
odmpy Interactive Client for Libby
----------------------------------------------------------------------
An unexpected error has occurred
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/odmpy/libby.py", line 357, in make_request
    res.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://sentry-read.svc.overdrive.com/chip/sync

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/odmpy/odm.py", line 846, in run
    synced_state = libby_client.sync()
                   ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/odmpy/libby.py", line 457, in sync
    res: Dict = self.make_request("chip/sync")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/odmpy/libby.py", line 366, in make_request
    ErrorHandler.process(http_err)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/odmpy/libby_errors.py", line 103, in process
    raise ClientError(
odmpy.libby_errors.ClientError: <odmpy.libby_errors.ClientError; http_status=403, msg='403 Client Error: Forbidden for url: https://sentry-read.svc.overdrive.com/chip/sync', error_response='{"result":"missing_chip"}''>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/odmpy/libby.py", line 357, in make_request
    res.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://sentry-read.svc.overdrive.com/chip/sync

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/odmpy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/odmpy/__main__.py", line 27, in main
    run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/odmpy/odm.py", line 846, in run
    synced_state = libby_client.sync()
                   ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/odmpy/libby.py", line 457, in sync
    res: Dict = self.make_request("chip/sync")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/odmpy/libby.py", line 366, in make_request
    ErrorHandler.process(http_err)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/odmpy/libby_errors.py", line 103, in process
    raise ClientError(
odmpy.libby_errors.ClientError: <odmpy.libby_errors.ClientError; http_status=403, msg='403 Client Error: Forbidden for url: https://sentry-read.svc.overdrive.com/chip/sync', error_response='{"result":"missing_chip"}''>`

**To Reproduce**
odmpy libby

**Version/Environment**
odmpy 0.8.1 [Python 3.12.3-darwin]

**Comment by cklann1** [comment]
Also getting this error using 
odmpy 0.8.1 [Python 3.9.2-linux]

**Comment by wtanksleyjr** [comment]
This is a new problem, but there's a simple fix:

Run `odmpy libby --reset` to clear the Libby registration, and then use the
Libby webapp or the phone app to generate a code, and run `odmpy libby` and
enter that code. It'll be back up again.

**Comment by leomem** [comment]
The reset did not work for me. After reset and reentering the code, downloading got the following error.
`python3.9/site-packages/odmpy/processing/odm.py", line 135, in process_odm
    raise ValueError("Unable to find Metadata in ODM")
ValueError: Unable to find Metadata in ODM`

The ODM file's content shows the error.

`<!DOCTYPE html>
<html>
<head>
<title>Access Error</title>
<style>pre { font: 12px/18px monospace; }</style>
</head>
<body>
<pre>
{
  &quot;result&quot;: &quot;missing_chip&quot;,
  &quot;policies&quot;: {
    &quot;privacy&quot;: &quot;https://company.cdn.overdrive.com/policies/privacy-policy&quot;,
    &quot;terms&quot;: &quot;https://company.cdn.overdrive.com/policies/terms-and-conditions.htm&quot;,
    &quot;jobs&quot;: &quot;https://company.overdrive.com/careers&quot;
  }
}
</pre>
</body>
<script type="text/javascript" src="/scripts/bridge.js"></script>
<script type="text/javascript">setTimeout(function(){BRIDGE.transmit({name:'sentry:access:error',dest:'client',error:{origin:'Sentry'}});},500);</script>
</html>
~          `

**Comment by wtanksleyjr** [comment]
Just to be clear, are you saying you see this when trying to download a
book? So you run `odmpy libby` and see your checked out books in the list
with a choice of what to do, but when you select one to download it errors
out as above?

-Wm

**Comment by leomem** [comment]
That's correct. I run `odmpy libby` and see my checked out books in the list.  When I tried to download any of them, I got the error. The generated .odm file contained the above error.  I have tried forceful reinstall too.

**Comment by wtanksleyjr** [comment]
Whew! Sorry about that. I'll have to step back and hope one of the experts can look at this, @ping maybe.

**Comment by jahlborn** [comment]
see #70

**Comment by wtanksleyjr** [comment]
OK, I have to confirm this - I'm now getting the same result. I kind of doubt they're attacking odmpy specifically, since they could do that just by sending GitHub a takedown notice; but for now it's the same effect.

**Comment by wtanksleyjr** [comment]
If you're in a situation where you're about to have a book expire while waiting for this, please note that the existing overdrive app for Windows should still work (if you're in a position to run it, of course). You'll have to download it from their site (paste this link into your browser press enter and then approve the security warning, don't try to click it or it'll just close the tab due to being an MSI file): `http://app.overdrive.com/downloads/ODMediaConsoleSetup.msi`; this is their official version so it's as safe as it was back when it was released. Go to your library's Overdrive site (usually something like lapl.overdrive.com). Sign in with your library card and last 4 digits of your phone number (or last 5 digits, or whatever). From there you should be able to get a download file, and that app can open it and use it to get the usual mp3 files. Not as nice as what we've become used to, but that's life!

If you need more metadata, you can download some nice JSON from an URL of the form `https://thunder.api.overdrive.com/v2/media/9722081` (I picked a random libby identifier there). It'll work even if you don't have the book checked out, so long as you have the book ID. Use `odmpy libby --exportloans loans.json` to find the book ID of the books you currently have checked out.

**Comment by leomem** [comment]
The overdrive windows program works. Thanks a lot. 
Not sure how to use the JSON metadata yet.

**Comment by cerinawithasea** [comment]
This is The error I am getting on both my Mac and windows laptop reset is not fixing it
The error will come after something similar to

Opening audiobook "When Trying to Return Home"...
Downloaded odm to "when-trying-to-return-home-9350409.odm"
An unexpected error has occurred
Then the error


Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/odmpy/odm.py", line 1210, in run
    process_odm(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/odmpy/processing/odm.py", line 135, in process_odm
    raise ValueError("Unable to find Metadata in ODM")
ValueError: Unable to find Metadata in ODM


I have tried different books

> The reset did not work for me. After reset and reentering the code, downloading got the following error. `python3.9/site-packages/odmpy/processing/odm.py", line 135, in process_odm raise ValueError("Unable to find Metadata in ODM") ValueError: Unable to find Metadata in ODM`
> 
> The ODM file's content shows the error.
> 
> `
> 
> <title>Access Error</title> <style>pre { font: 12px/18px monospace; }</style>
> {
>   "result": "missing_chip",
>   "policies": {
>     "privacy": "https://company.cdn.overdrive.com/policies/privacy-policy",
>     "terms": "https://company.cdn.overdrive.com/policies/terms-and-conditions.htm",
>     "jobs": "https://company.overdrive.com/careers"
>   }
> }
> <script type="text/javascript" src="/scripts/bridge.js"></script> <script type="text/javascript">setTimeout(function(){BRIDGE.transmit({name:'sentry:access:error',dest:'client',error:{origin:'Sentry'}});},500);</script> ~ `

**Comment by mitrian7** [comment]
> Go to your library's Overdrive site (usually something like lapl.overdrive.com). Sign in with your library card and last 4 digits of your phone number (or last 5 digits, or whatever). From there you should be able to get a download file, and that app can open it and use it to get the usual mp3 files. Not as nice as what we've become used to, but that's life!

So, this is cool, thank you.  **But also worth noting**, you don't even need the desktop app.  Just download the odm file from the overdrive site as you described, then you can use that odm file with odmpy directly.  For example, if you want the benefits of merging with chapter metadata that odmpy does so nicely, you can run something like this:

`odmpy dl "title.odm" -m --mergeformat m4b --mergecodec aac`

... where `title.odm` is what you downloaded from the overdrive site.

**Comment by moviebrain** [comment]
Is this something that can even be fixed? The browser extensions stopped working about 48 hours prior to this stopping, so it seems like one by one these tools are being targeted specifically. Honestly I’d love if this just happens to be a back end change that needs a tweak but I’d fully understand any and all contributors not wanting to engage in a cat and mouse endless game of “fix the authentication”

If it can’t be fixed I’ll greatly miss the ability to play library audiobooks on the unsupported kids-boxy- speaker-things we have, it’s genuinely reignited my their love of stories. Thanks @ping for everything you did, in advance.

**Comment by mitrian7** [comment]
> Is this something that can even be fixed?

While I do hope there's a solution, I think even if it can't be fixed, the workaround (see the post above) is mostly painless, it just adds the extra step of downloading the .odm manually from OverDrive.  You can still get all the power and benefits of odmpy here.

**Comment by jahlborn** [comment]
> > Is this something that can even be fixed?
> 
> While I do hope there's a solution, I think even if it can't be fixed, the workaround (see the post above) is mostly painless, it just adds the extra step of downloading the .odm manually from OverDrive. You can still get all the power and benefits of odmpy here.

i certainly hope there is a solution as well.  the workaround is manual, and the power of this library is that i can automate the process.  

maybe this library could be patched to grab the odm files from the overdrive website...

**Comment by bckelly1** [comment]
I've been taking a look at this and to me it looks like they've changed how the JWT token is structured. The old JWT is very different than the one the web UI is using. Not sure if it's a red herring but it may be that the python client needs to use a different method to fetch the JWT.

Not an expert, and I'll look deeper when I get some time.

**Comment by jahlborn** [comment]
in theory, this _should_ be fixable.  if the libby app and the libby webpage can load the data, then it should be possible to determine what api calls they are making and reproduce them.  granted, they can use a ton of obfuscation to make that difficult...

**Comment by Prajna-Karuna** [comment]
> From there you should be able to get a download file

I have looked everywhere and can't find a way to download the odm. Neither from the overdrive.com site nor from the installed msi file (which doesn't allow me to login, so it is just an empty overdrive GUI)
Can you be more specific on how to download the odm?

**Comment by wtanksleyjr** [comment]
Prajnah, would you mind identifying which library you are using, and I'll
find the right site for you?

For example: I'm using Los Angeles Public Library, so to get ODMs I go to
lapl.overdrive.com (notice the abbreviation for the library's name, it's
not always that simple but sometimes is), log in, click "My Account",
choose "Loans", and on any specific audiobook title, click "Have
Overdrive?", and you'll see a button appear, click it and you'll download
the ODM.

BTW you can open that in the Windows Overdrive app, but if you're using
odmpy already it turns out you can just use odmpy to do all the downloading
using the same file. See above for instructions.

-Wm

**Comment by moviebrain** [comment]
> Prajnah, would you mind identifying which library you are using, and I'll find the right site for you? For example: I'm using Los Angeles Public Library, so to get ODMs I go to lapl.overdrive.com (notice the abbreviation for the library's name, it's not always that simple but sometimes is), log in, click "My Account", choose "Loans", and on any specific audiobook title, click "Have Overdrive?", and you'll see a button appear, click it and you'll download the ODM. BTW you can open that in the Windows Overdrive app, but if you're using odmpy already it turns out you can just use odmpy to do all the downloading using the same file. See above for instructions.
> […](#)
> -Wm

My local branch overdrive site hid the download link for the odm because I was using a hardware/software combo that the Overdrive for (win/mac) didn’t support. I had to change the user-agent string in Firefox about:config to an appropriate OS version and then the “download” button appeared again.

**Comment by bckelly1** [comment]
> in theory, this _should_ be fixable. if the libby app and the libby webpage can load the data, then it should be possible to determine what api calls they are making and reproduce them. granted, they can use a ton of obfuscation to make that difficult...

I just did this and I noticed a couple things. The JWT in use actually changes at least 3 times. Also, the JWT is really weird. It's not a standard JWT format that I recognize. They are much longer and they have literally `...` in the middle. It doesn't parse as a valid JWT. 

Anyway, I did actually get it to work for books, but audiobooks has a problem that I have to debug. You can splice the contents/results of two different calls and merge them into the libby.json replacing the chip, identity and __libby_sync_code fields.

```
An unexpected error has occurred
Traceback (most recent call last):
  File "/usr/src/app/odmpy/odm.py", line 1210, in run
    process_odm(
  File "/usr/src/app/odmpy/processing/odm.py", line 135, in process_odm
    raise ValueError("Unable to find Metadata in ODM")
ValueError: Unable to find Metadata in ODM
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/app/odmpy/__main__.py", line 35, in <module>
    main()
  File "/usr/src/app/odmpy/__main__.py", line 27, in main
    run()
  File "/usr/src/app/odmpy/odm.py", line 1210, in run
    process_odm(
  File "/usr/src/app/odmpy/processing/odm.py", line 135, in process_odm
    raise ValueError("Unable to find Metadata in ODM")
ValueError: Unable to find Metadata in ODM
```

**Comment by ziferius** [comment]
> > Prajnah, would you mind identifying which library you are using, and I'll find the right site for you? For example: I'm using Los Angeles Public Library, so to get ODMs I go to lapl.overdrive.com (notice the abbreviation for the library's name, it's not always that simple but sometimes is), log in, click "My Account", choose "Loans", and on any specific audiobook title, click "Have Overdrive?", and you'll see a button appear, click it and you'll download the ODM. BTW you can open that in the Windows Overdrive app, but if you're using odmpy already it turns out you can just use odmpy to do all the downloading using the same file. See above for instructions.
> > […](#)
> > -Wm
> 
> My local branch overdrive site hid the download link for the odm because I was using a hardware/software combo that the Overdrive for (win/mac) didn’t support. I had to change the user-agent string in Firefox about:config to an appropriate OS version and then the “download” button appeared again.

You can always go to https://www.overdrive.com..... in the top right there is a 'Find Library' link.  Click that, and key in your zip and it'll find your library.

**Comment by jahlborn** [comment]
looks like some of the extensions have been fixed.  just used the latest version of the firefox libby downloader extension and it worked great.

**Comment by wtanksleyjr** [comment]
Whatever's going on is kinda subtle - I've seen non-working apps with no
fixes begin working again, and then stop working. It's possible there are
some servers still running old code and if you get directed to them old
apps work. OTOH, I don't know for sure. Maybe the breaking change is more
subtle than it seems at first.

**Comment by jahlborn** [comment]
> I just did this and I noticed a couple things. The JWT in use actually changes at least 3 times. Also, the JWT is really weird. It's not a standard JWT format that I recognize. They are much longer and they have literally `...` in the middle. It doesn't parse as a valid JWT.

@bckelly1 i did a little digging online and i saw some stuff mentioning "opaque" tokens for oauth2.  for instance, auth0 has an opaque token which has two periods in the middle of it, which is not a valid jwt.  not sure if that actually _helps_ you in anyway, but just thought i'd throw it out there. 

https://www.reddit.com/r/aws/comments/v16z4b/if_a_jwt_contains_two_consecutive_period/
https://community.auth0.com/t/why-my-token-has-2-dots-in-it/106186

**Comment by bckelly1** [comment]
I think there is a deeper change that will be required, though it looks easy maybe? I stumbled across [this](https://github.com/bookbonobo/libby-download-extension/pull/195) while looking for answers and it seems to mention similar topics. However, I don't see how the code actually fixed the problem so I'll have to dig a little deeper when I get some time.

**Comment by jahlborn** [comment]
some progress appears to have been made in #71

**Comment by jahlborn** [comment]
@bckelly1 have you been able to figure anything else out?

**Comment by bckelly1** [comment]
> @bckelly1 have you been able to figure anything else out?

Not much, I haven't put a lot of effort into it. I did find that this workaround in the [firefox plugin](https://github.com/bookbonobo/libby-download-extension/issues/206#issuecomment-2113018270) is working, but it is highly manual. In theory, [this could work](https://github.com/bookbonobo/libby-download-extension/issues/206#issuecomment-2126156302) with odmpy but I have yet to make it work for me. They embedded the spine info into an image, but I must not understand the instructions because it hasn't worked for me.

**Comment by wtanksleyjr** [comment]
Tonight my odmpy libby just fell out of sync, and there doesn't seem to be a way to get the 8-digit-code to make it come back into sync. So from here on out, it's odm downloads only.

**Comment by j-antunes** [comment]
@wtanksleyjr - I tried it today and I was able to get the 8 digit code, by clicking on "Are you connecting sonos speakers"
![image](https://github.com/user-attachments/assets/dc9f25a2-182d-4000-8e6f-691dd82628b7)

![image](https://github.com/user-attachments/assets/7da70ac6-ff82-48cf-be7c-36edc48002ba)

**Comment by David-Alton** [comment]
> @wtanksleyjr - I tried it today and I was able to get the 8 digit code, by clicking on "Are you connecting sonos speakers"
> 

Did this allow you to auto download your audiobooks?

**Comment by coloradoruss** [comment]
The libby audiobook download is broken.  The Firefox and Chrome plugins are
broken as well.  The only thing that works is dl - I hope someone can
get the libby thing working at some point, but at least we have something.
You have to get the odm file from *your library*.overdrive.com, have
overdrive..., download mp3... and run dl on the odm file.  The command I
use is odmpy dl -c -m -j -k -mergeformat m4b



Russ




*Confidentiality Notice: This message may contain confidential and/or
privileged information.  If you are not the addressee or authorized to
receive this for the addressee, you must not use, copy, disclose, or take
any action based on this message or any information herein.  If you have
received this message in error, please advise the sender immediately by
reply e-mail and delete this message.Non-Binding and Expiration Disclaimer:
Content of emails, to include any included links and attachments thereto,
sent or received shall not create a binding contract or be construed to be
conveyance or acceptance of any offer, contract or any other agreement,
whatsoever, nor shall the same be binding on any party until a written
contract is signed by all parties.  In the event a bona fide, signed offer
is conveyed via email, the same shall expire, if not accepted and fully
executed by all parties, upon the latter of its explicitly stated
expiration date or, if such a date is not specified, twenty-four hours from
its initial transmission by the offeror and shall thereafter not be binding
on any party.*




*Wire Fraud Notice: Never trust wiring instructions sent via email. Cyber
criminals are hacking email accounts and sending emails with fake wiring
instructions. These emails are convincing and sophisticated. Always
independently confirm wiring instructions in person or via a telephone call
to a trusted and verified phone number. Never wire money without
double-checking that the wiring instructions are correct.Affiliated
Business Disclosure: I have an ownership interest in both Pink Realty, Inc
and Pink Realty Rentals and work closely with both companies and their
agents and employees, my real estate license and my brokerage activity is
with Pink Realty Rentals.*

**Comment by codyc1515** [comment]
> @wtanksleyjr - I tried it today and I was able to get the 8 digit code, by clicking on "Are you connecting sonos speakers"

Same here. Looks like the way forward is using Passkeys.

**Comment by David-Alton** [comment]
> Same here. Looks like the way forward is using Passkeys.

For the record, I believe this ticket is to record that there's an issue auto-downloading audiobooks.

This solves an issue, but not the one originally ticketed.

**Comment by wtanksleyjr** [comment]
Yes, the "odmpy dl" subcommand still works (magnificently!), whew, but once
I use the Sonos choice, so does the "odmpy libby --exportloans" command,
which allows me to figure out which ODM file goes with which Libby
metadata, generate detailed audiobookshelf data, warn if I haven't
downloaded an ODM file for a book that's about to expire, and so on.

**Comment by j-antunes** [comment]
@wtanksleyjr - How are you getting the odm file?

**Comment by coloradoruss** [comment]
You have to get the odm file from *your library*.overdrive.com, have
overdrive..., download mp3...

I think you can go to overdrive.com and search for your library's url.  For
example, TN is https://reads.overdrive.com/

**Comment by ziferius** [comment]
Definitely go to https://www.overdrive.com/libraries.  There are folks that
are passing around spreadsheets of URLs for libraries and it's not needed.

**Comment by jahlborn** [comment]
intersting, looks like someone made some progress here, i wonder if it is helpful to this project: https://github.com/bookbonobo/libby-download-extension/pull/240

**Comment by wtanksleyjr** [comment]
Libby sign-in is failing with a new error, blocking Sonos and Android choices now. It also seems to destroy existing signins, the error I see is a certificate authentication failure, Libby seems to be sending an HTTPS certificate that doesn't match the machine it's coming from. This is reported in #78 .

**Comment by wtanksleyjr** [comment]
Regarding #78 someone has posted a fix at https://github.com/jordkh/odmpy , this does not fix the major problem here but it does allow Libby login once again - you still have to manually download the odm file from your library's Loans page on overdrive.com, but you can again use Libby's list of checked out books.

**Comment by wtanksleyjr** [comment]
The command I just ran to install this was `python3 -m pip install git+https://git@github.com/jordkh/odmpy --upgrade --force-reinstall`

**Comment by jahlborn** [comment]
@wtanksleyjr can you clarify specifically what should be working now?  being able to download files with odmpy given an odm file has been working the whole time.

**Comment by wtanksleyjr** [comment]
Logging in to Libby works again (that is, syncing your odmpy libby account
with some other Libby machine), which means you can now get a list of
checked-out books. I use that to get detailed metadata from Libby on each
ODM book, as well as knowing when I checked out a book but forgot to
download its ODM.

-Wm

**Comment by wtanksleyjr** [comment]
There are people working on making this work within browser extensions.

For example: https://github.com/bookbonobo/libby-download-extension/pull/240

I don't think we've actually lost yet - the problem is that nobody here has the expertise to work on the problem.

**Comment by Ritergeek** [comment]
As of today, Overdrive has disabled the option to Download in Overdrive for Windows format on the Overdrive site for my library and apparently all subscribing libraries. This apparently means odm files. Does this totally tank the Libby Downloader potential?

**Comment by wtanksleyjr** [comment]
It doesn't change anything about the Libby downloader - specifically, we haven't figured out how to get its login token. Once the login token is fetched (which currently can only be done in a web browser), the files downloaded are the same MP3 files we always received before.

However, for now odmpy can only do one thing: show you what files you have checked out (`odmpy libby`). Everything else is completely disabled.

**Comment by jahlborn** [comment]
https://github.com/ping/odmpy/issues/78#issuecomment-2486773994

**Comment by vcalv** [comment]
>  Once the login token is fetched (which currently can only be done in a web browser), the files downloaded are the same MP3 files we always received before.

This is not true. The Libby mp3 files have no metadata whatsoever, whereas the mp3 files from odm have metadata, including chapter information and thumbnails.

**Comment by wtanksleyjr** [comment]
Whoops, thank you for the entirely apropos correction; I never use that data so didn't notice it was missing. I've been using Overdrive's JSON data endpoint, but that doesn't have chapter data, so I've been missing that this whole time without noticing it.

**Comment by vcalv** [comment]
> Overdrive's JSON data endpoint

Can you give more information regarding that?

Or just point to the source code.

**Comment by wtanksleyjr** [comment]
Yes, you can get a lot of metadata without being logged in or anything,
just take the book's Libby number (which will be the last part of its URL
on Overdrive, I'll give an example) and add it to the end of this http
address: 'https://thunder.api.overdrive.com/v2/media/'.

So for example, I go to my Loans page, click on the title of a random book,
and up comes the book's page, https://lapl.overdrive.com/media/65692. See
the number at the end? Copy it onto that URL above, so it becomes
https://thunder.api.overdrive.com/v2/media/65692 . Now click that and view
it in your browser, or use Python's requests library to download it and
JSON to munge it about.

The only problem is that the libby number isn't contained in the Overdrive
file, I don't know of any reliable way to get one from the other. Every way
that works has exceptions that don't work.

-Wm

**Comment by vcalv** [comment]
Oh! That!

I've seen that. No chapter information though.

My real problem in the libby extension I've created is that I can't get the chapter information.

Which means that in order to get it I'd have to get it from the actual HTML/DOM listen page.

With that the extension would be workable, the only drawback is that you have to seek manually to eventually trigger the download of all parts.

For now I'm still able to use the old overdrive site to download odm files and my usual pipeline works.

Download odm => download mp3s => convert to opus with chapters and thumbnails.

When that fails (and it will) then maybe I'll take the time to look into doing that with libby.

**Comment by wtanksleyjr** [comment]
It looks like the bookmarklet solution no longer works - it fails to replace correctly, leaving mp3 in the string (I'm not sure why), but even if I replace manually the result is a dead link. I don't think they've actually taken down the ODM files, but they've definitely worked around the bookmarklet and the Firefox extension.
I wouldn't expect any of this to keep working anymore, this kind of thing is a losing battle.

**Comment by wtanksleyjr** [comment]
Also, @vcalv 's solution was taken down - hope you're OK.

**Comment by vcalv** [comment]
People that have installed the extension still have it, but it's useless. I recommend disabling it.

No `odm` download =>nothing along those lines will work (bookmarklet, underdrive, etc).

**Comment by newwooddog** [comment]
Oh rats.  And the bookmarklet was _so_ nice.  Now it's back to wandering in the wilderness

**Comment by wtanksleyjr** [comment]
odmpy's libby logins stopped working for me (and apparently others), so we're tracking that in #83 because the Calibre plugin can still do it (!).

**Comment by kernalbin** [comment]
I skimmed through this a couple days ago when I wanted to download something, not seeing a lot of hope here. So I decided I had a new project. Its a very unclean method, but I can successfully download a book from overdrive, including chapter info all scraped from the in browser listener.

My progress here: [https://github.com/kernalbin/odmpy-ng](https://github.com/kernalbin/odmpy-ng)

Currently it will log into overdrive, list loans, and then download the selected one, adding in chapter and other metadata. It takes a whole lot longer than before. But it works, most of the time.

My experience with web scraping is extremely limited, and so I'm sure this looks like garbage to most of you pros, but I got it to work so I still feel superior to you /s.

**Comment by wtanksleyjr** [comment]
I love the idea, it seems like the right way to do this. I'm not having any
luck setting it up, could you give something ... maybe just a narrative,
maybe a list of prerequisites to be installed using pip (or whatever),
anything would be helpful... For example, how am I supposed to get the
cookies?

-Wm

**Comment by Samcfuchs** [comment]
Sad to see this is no longer working. Hate to be a downer, but maybe the README should be updated to mention the tool is deprecated? Would have saved me 15 minutes. Kudos nevertheless to the contributors, wish I had found this when it still worked.

**Comment by wtanksleyjr** [comment]
Unfortunately the author hasn't updated this site at all in a long time, even before it stopped working.

I would link to "odmload" and "odmpy-ng" under my Github account except that this thread is probably being monitored (some people have had their accounts limited). Try it, though.

**Comment by BMmubeez** [comment]
I’ve been tracking similar raise_for_status() errors lately. When the script fails here, it’s often because the target API is returning a 403 or 429 response due to updated bot detection. To stabilize this, I’ve found these steps helpful:
Session Headers: Ensure you are passing a complete browser-like header set (specifically User-Agent and Referer).
Request Pacing: Implement a randomized sleep timer between calls to avoid hitting the API rate limit.
Proxy Rotation: If you are hitting consistent blocks, rotating through residential proxies—like Magnetic Proxy—is the best way to maintain a clean IP reputation.
Backoff: Add a simple exponential backoff to your retry logic to handle 429 status codes gracefully.

**Comment by wtanksleyjr** [comment]
This is a completely different situation - this API was changed to return
encrypted data, and the author (ping) of odmpy was gone so the program's
dead now.
