### ISSUE TITLE
ODM File Request Fails

### ISSUE THREAD

**Issue by alp1n3-dev** [ping/odmpy#73]
**Describe the problem**
A clear and concise description of what the bug/error is. If there is an error traceback dump, paste the text here (please avoid screenshots).

Upon attempting to download an audiobook, the program fails. It appears it is failing to acquire the auth chip at some stage of the process resulting in the metadata not being able to be pulled for the audiobook.

Contents of the ODM File:
```
{
  "result": "missing_chip",
  "policies": {
    "privacy": "https://company.cdn.overdrive.com/policies/privacy-policy",
    "terms": "https://company.cdn.overdrive.com/policies/terms-and-conditions.htm",
    "jobs": "https://company.overdrive.com/careers"
  }
}
```

Error:
```Download. Choose from 1-8 (separate choices with a space or leave blank to quit),
then press enter: 1
Opening audiobook "SNIP"...
Already downloaded odm file SNIP-1234512.odm
An unexpected error has occurred
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/odmpy/odm.py", line 1210, in run
    process_odm(
  File "/opt/homebrew/lib/python3.11/site-packages/odmpy/processing/odm.py", line 135, in process_odm
    raise ValueError("Unable to find Metadata in ODM")
ValueError: Unable to find Metadata in ODM
Traceback (most recent call last):
  File "/opt/homebrew/bin/odmpy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/odmpy/__main__.py", line 27, in main
    run()
  File "/opt/homebrew/lib/python3.11/site-packages/odmpy/odm.py", line 1210, in run
    process_odm(
  File "/opt/homebrew/lib/python3.11/site-packages/odmpy/processing/odm.py", line 135, in process_odm
    raise ValueError("Unable to find Metadata in ODM")
ValueError: Unable to find Metadata in ODM
```

**To Reproduce**
Please include the full command used, for example `odmpy libby --direct`

1. `odmpy libby`
2. Select any audiobook.
3. Observe failure message.

**Version/Environment**
Please paste the contents of `odmpy --version` here.

odmpy 0.8.1 [Python 3.11.6-darwin]

**Comment by alp1n3-dev** [comment]
Closing as dupe. Apologies.
