### ISSUE TITLE
odmpy libby --latest 1 consistently fails for the past few days

### ISSUE THREAD

**Issue by bedge** [ping/odmpy#74]
**Describe the problem**

I've been using 
```
odmpy libby --latest 10
```
for ages as a "grab all my stuff" command. It skips he books I already have and simply pulls what's new.

This started failing a couple of days ago.

Possibly related to: https://www.reddit.com/r/Calibre/comments/1cd6cqd/im_suddenly_getting_a_403_when_i_try_to_use_the/ ?

Will try generating a new key.

**To Reproduce**

```
❯ odmpy libby --latest 1

odmpy Interactive Client for Libby
----------------------------------------------------------------------
An unexpected error has occurred
Traceback (most recent call last):
  File "/Users/bedge/.pyenv/versions/default/lib/python3.11/site-packages/odmpy/libby.py", line 357, in make_request
    res.raise_for_status()
  File "/Users/bedge/.pyenv/versions/default/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://sentry-read.svc.overdrive.com/chip/sync

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bedge/.pyenv/versions/default/lib/python3.11/site-packages/odmpy/odm.py", line 846, in run
    synced_state = libby_client.sync()
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/bedge/.pyenv/versions/default/lib/python3.11/site-packages/odmpy/libby.py", line 457, in sync
    res: Dict = self.make_request("chip/sync")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bedge/.pyenv/versions/default/lib/python3.11/site-packages/odmpy/libby.py", line 366, in make_request
    ErrorHandler.process(http_err)
  File "/Users/bedge/.pyenv/versions/default/lib/python3.11/site-packages/odmpy/libby_errors.py", line 103, in process
    raise ClientError(
odmpy.libby_errors.ClientError: <odmpy.libby_errors.ClientError; http_status=403, msg='403 Client Error: Forbidden for url: https://sentry-read.svc.overdrive.com/chip/sync', error_response='{"result":"missing_chip"}''>
Traceback (most recent call last):
  File "/Users/bedge/.pyenv/versions/default/lib/python3.11/site-packages/odmpy/libby.py", line 357, in make_request
    res.raise_for_status()
  File "/Users/bedge/.pyenv/versions/default/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://sentry-read.svc.overdrive.com/chip/sync

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bedge/.pyenv/versions/default/bin/odmpy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/bedge/.pyenv/versions/default/lib/python3.11/site-packages/odmpy/__main__.py", line 27, in main
    run()
  File "/Users/bedge/.pyenv/versions/default/lib/python3.11/site-packages/odmpy/odm.py", line 846, in run
    synced_state = libby_client.sync()
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/bedge/.pyenv/versions/default/lib/python3.11/site-packages/odmpy/libby.py", line 457, in sync
    res: Dict = self.make_request("chip/sync")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bedge/.pyenv/versions/default/lib/python3.11/site-packages/odmpy/libby.py", line 366, in make_request
    ErrorHandler.process(http_err)
  File "/Users/bedge/.pyenv/versions/default/lib/python3.11/site-packages/odmpy/libby_errors.py", line 103, in process
    raise ClientError(
odmpy.libby_errors.ClientError: <odmpy.libby_errors.ClientError; http_status=403, msg='403 Client Error: Forbidden for url: https://sentry-read.svc.overdrive.com/chip/sync', error_response='{"result":"missing_chip"}''>
```

**Version/Environment**
Please paste the contents of `odmpy --version` here.

**Comment by bedge** [comment]
Finally found the option to reset the creds. It's not exactly obvious.

Now the error is different.

Reset credentials:
```
❯ odmpy  libby --reset
odmpy Interactive Client for Libby
----------------------------------------------------------------------
Cleared settings.

❯ odmpy libby
odmpy Interactive Client for Libby
----------------------------------------------------------------------
A Libby setup code is needed to allow odmpy to interact with Libby.
To get a Libby code, see https://help.libbyapp.com/en-us/6070.htm

Enter the 8-digit Libby code and press enter: 05549258
Login successful.

Found 2 loans.
.....

Download. Choose from 1-2 (separate choices with a space or leave blank to quit),
then press enter:
```

Back to my usual download recipe:
```
❯ odmpy libby --latest 12
odmpy Interactive Client for Libby
----------------------------------------------------------------------
Non-interactive mode. Downloading latest 12 loans...
Opening audiobook "Quackery"...
Downloaded odm to "quackery-4148466.odm"
An unexpected error has occurred
Traceback (most recent call last):
  File "/Users/bedge/.pyenv/versions/default/lib/python3.11/site-packages/odmpy/odm.py", line 983, in run
    process_odm(
  File "/Users/bedge/.pyenv/versions/default/lib/python3.11/site-packages/odmpy/processing/odm.py", line 135, in process_odm
    raise ValueError("Unable to find Metadata in ODM")
ValueError: Unable to find Metadata in ODM
Traceback (most recent call last):
  File "/Users/bedge/.pyenv/versions/default/bin/odmpy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/bedge/.pyenv/versions/default/lib/python3.11/site-packages/odmpy/__main__.py", line 27, in main
    run()
  File "/Users/bedge/.pyenv/versions/default/lib/python3.11/site-packages/odmpy/odm.py", line 983, in run
    process_odm(
  File "/Users/bedge/.pyenv/versions/default/lib/python3.11/site-packages/odmpy/processing/odm.py", line 135, in process_odm
    raise ValueError("Unable to find Metadata in ODM")
ValueError: Unable to find Metadata in ODM
```

**Comment by bedge** [comment]
Interactive downloads fail the same way.

**Comment by aNullValue** [comment]
This is almost certainly a duplicate of #69 even if the error messages aren't exactly the same.

**Comment by wtanksleyjr** [comment]
I recommend closing this as a duplicate and moving to that report for best
practices.

The simplest solution, although it's only partial, is to manually download
the ODM from the Overdrive version of the site (you can still do that even
if you check out with Libby), and then pass that ODM file to odmpy, which
can download it. You can also download the Libby metadata if you want (I
explain a way), since Overdrive doesn't give you very much.

**Comment by bedge** [comment]
Make sense, appreciate the response.
